### ISSUE TITLE
「web会議」に盛り込むコンテンツ案

### ISSUE THREAD

**Issue by caffisenna** [Scout-Association-of-Japan/DX-promotion-guidelines#2]
盛り込みコンテンツの提案です。

- 『うちの中が映るのはかなわん！』
- 『どうしてオンライン会議で、声が聞きやすい人と聞きにくい人がいるの？』

**Comment by 07JP27** [comment]
@caffisenna 
ガイドというよりFAQにまとめる感じでしょうか？
それぞれ１つ１ページだとコンテンツ的に弱いですよね・・・。
と思いますが、ページ構成はおまかせします。

**Comment by caffisenna** [comment]
@07JP27 
FAQ一覧から子ページ(anchorタグ?)にジャンプ形式ですかねぇ。
書きつつ検討してみます。

**Comment by 07JP27** [comment]
- ハウリングが起きるのはなぜ？
