### ISSUE TITLE
DXのロゴマークが欠落している

### ISSUE THREAD

**Issue by caffisenna** [Scout-Association-of-Japan/DX-promotion-guidelines#21]
## 起こっている問題 / The Problem
- DX推進室のロゴマークが欠落している

## スクリーンショット / Screenshot

![screenshot 2020-08-27 21 18 34](https://user-images.githubusercontent.com/1632947/91441416-1e158580-e8ab-11ea-9ead-816c7c09886c.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- タイトルの下部にロゴマークを描画する

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://scout-association-of-japan.github.io/DX-promotion-guidelines/Home.html にアクセス

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by caffisenna** [comment]
画像アップします

**Comment by 07JP27** [comment]
@caffisenna 
DXロゴ無いほうがスッキリするような気も・・・・。
どうしましょう。

**Comment by caffisenna** [comment]
@07JP27 
トップにはあってもいいかもしれないけど、全ページだとうるさいかも。
無しでいいかなー

**Comment by 07JP27** [comment]
@caffisenna 
ヘッダーの左上に小さく表示とかできないんですかね。よくサイトにあるロゴみたいな感じで
