### ISSUE TITLE
「よくある質問」をMD化

### ISSUE THREAD

**Issue by 07JP27** [Scout-Association-of-Japan/DX-promotion-guidelines#25]
## 改善詳細 / Details of Improvement
- 現在G siteで運用されている「[よくある質問](https://sites.google.com/scout.jp/meet/%E3%82%88%E3%81%8F%E3%81%82%E3%82%8B%E8%B3%AA%E5%95%8F)」をMD化して本リポジトリに移行する。

**Comment by caffisenna** [comment]
こちらも同時進行中です。
一部修正が必要

**Comment by 07JP27** [comment]
@caffisenna 
meetだけじゃなくなるので製品別にするとかセクション分けなど考えないといけないかもしれないですね。

**Comment by caffisenna** [comment]
issueとしては解決済みのため手動にてclose (自動で閉じなかったため)
