### ISSUE TITLE
Meetの有料表記を分かりやすく修正する

### ISSUE THREAD

**Issue by caffisenna** [Scout-Association-of-Japan/DX-promotion-guidelines#43]
## 改善詳細 / Details of Improvement
- [どの会議ツールを選んだらいいの？](https://scout-association-of-japan.github.io/DX-promotion-guidelines/web-meeting-guide/WhatShouldIChoose.html) で記載されているMeetの有料表記をデジタルツール配付プログラムに合わせた分かりやすい表記に修正する

**Comment by 07JP27** [comment]
合わせてzoomのセキュリティに関する勧告も削除してください。
zoom5.0のアップデートで解消されました。

**Comment by caffisenna** [comment]
(提供がある場合)`各社が提供する最新版の使用を推奨` という旨で盛り込もうと思います。

**Comment by caffisenna** [comment]
review & mergeありがとうございました
