### ISSUE TITLE
README.md の誤字修正, 公開サイトへのリンクを追加する

### ISSUE THREAD

**Issue by kazuemon** [Scout-Association-of-Japan/DX-promotion-guidelines#71]
### README.md の誤字修正

`Issuesにあるタスクや発見した不具合等の等の開発にご協力ください。`
→`Issuesにあるタスクや発見した不具合等の修正にご協力ください。` が正しい?

### 公開サイトへのリンクを追加

- リポジトリの詳細部分(下記画像のリンクの場所) に公開サイトへのリンクを追加
https://scout-association-of-japan.github.io/DX-promotion-guidelines/Home.html

![image](https://user-images.githubusercontent.com/12812934/96726495-019a5300-13ed-11eb-975b-5e9353334c1c.png)

もしくは README.md でもいいかと考えてます。

**Comment by kazuemon** [comment]
元々READMEにどっちもぶっこむのが良いかと思ってたので、Issue分割できてなくてすみません...

**Comment by caffisenna** [comment]
@kazuemon 
はじめまして! DX推進室の只野です。
typoなどはどんどんPRください。

公開サイトへのリンクはREADME.mdへの記述でもいいかもしれないですね。
repoのトップにincludeされて表示されるので。

**Comment by kazuemon** [comment]
@caffisenna 了解しました。対応します！

**Comment by caffisenna** [comment]
@kazuemon 
よろしくお願いいたします。
ごめんなさい。README.mdには既にHOMEへのリンクがありました。この表記を分かりやすく変更するのもありですね!

**Comment by kazuemon** [comment]
@caffisenna ですね、既存のHOMEは確かリポジトリ内のHOME.mdへのリンクだったかと思うので、少し表記検討します！

**Comment by 07JP27** [comment]
Aboutに入れておいて損はないと考えましたのでとりあえずリポジトリのAboutにはトップページへのURL追加しました。

**Comment by kazuemon** [comment]
@07JP27 了解しました、ありがとうございます。
今別件で少し立て込んでいるので、後ほどPR送ります。
