### ISSUE TITLE
パスワード再設定フォームへのリンクを張る

### ISSUE THREAD

**Issue by caffisenna** [Scout-Association-of-Japan/DX-promotion-guidelines#81]
## 起こっている問題 / The Problem
- パスワード再設定フォームへのリンク文字列がリンクタグで囲われていないためジャンプできない

## スクリーンショット / Screenshot

![G Suiteへのログイン方法 | DX-promotion-guidelines 2021-02-09 20-30-45](https://user-images.githubusercontent.com/1632947/107358479-c7c59780-6b16-11eb-9622-473b7a093ee6.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- フォームへのリンクをリンクタグで囲う

## 起こっている問題の再現手段 / Steps to Reproduce
1. [G Suiteへのログイン方法](https://scout-association-of-japan.github.io/DX-promotion-guidelines/gsuite/howtologin.html)にアクセスし、ページ最下部の表記を確認する

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by n-takano** [comment]
やります！
