### ISSUE TITLE
ホストによるMeetの強制終了

### ISSUE THREAD

**Issue by dunesfolk** [Scout-Association-of-Japan/DX-promotion-guidelines#84]
## ホストによるMeetの強制終了機能の説明を追加する
Google Meetでホストが通話を終了する時に、次の２つが選べるようになった
- 終了せずに自分だけ退出
- 通話を終了（ホストによる強制終了）

**Comment by dunesfolk** [comment]
書きます

**Comment by 07JP27** [comment]
@dunesfolk contributingありがとうございます。こちら進捗いかがでしょうか。

**Comment by dunesfolk** [comment]
次のプルリクエストで本件完了しました。
https://github.com/Scout-Association-of-Japan/DX-promotion-guidelines/pull/85
すいません、issueの閉じ方を自分が分かっておりません。
